blog/urls.py
from django.urls import path

from blog.views import PostCreateView, PostListView, PostDetailView, PostUpdateView, PostDeleteView, \
    toggle_is_published, PostArchiveListView
from blog.apps import BlogConfig

app_name = BlogConfig.name

urlpatterns = [
    path('create/', PostCreateView.as_view(), name='create'),
    path('', PostListView.as_view(), name='list'),
    path('edit/<int:pk>/', PostUpdateView.as_view(), name='edit'),
    path('view/<int:pk>/', PostDetailView.as_view(), name='view'),
    path('delete/<int:pk>/', PostDeleteView.as_view(), name='delete'),
    path('is_published/<int:pk>/', toggle_is_published, name='is_published'),
    path('archive/', PostArchiveListView.as_view(), name='archive'),

]

config/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls', namespace='main')),
    path('blog/', include('blog.urls', namespace='blog')),
    path('users/', include('users.urls', namespace='users')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/models.py
from django.db import models

NULLABLE = {'blank': True, 'null': True}


class Post(models.Model):
    title = models.CharField(max_length=200, verbose_name="Заголовок")
    preview_img = models.ImageField(upload_to='posts/', verbose_name="Превью", **NULLABLE)
    content = models.TextField(verbose_name="Содержимое")
    date_posted = models.DateTimeField(auto_now_add=True, verbose_name="Дата публикации")
    author = models.CharField(max_length=50, verbose_name="Автор")
    slug = models.TextField(max_length=150, verbose_name="slug", **NULLABLE)
    is_published = models.BooleanField(default=True, verbose_name="Опубликовано")
    views_count = models.IntegerField(default=0, verbose_name="Просмотры")

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = "Публикация"
        verbose_name_plural = "Публикации"

blog/views.py
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin
from django.shortcuts import render, get_object_or_404, redirect
from django.urls import reverse_lazy, reverse
from django.views.generic import CreateView, UpdateView, ListView, DetailView, DeleteView
from pytils.translit import slugify

from blog.models import Post


class PostCreateView(LoginRequiredMixin, PermissionRequiredMixin, CreateView):
    model = Post
    fields = ('title', 'content', 'author', 'preview_img')
    permission_required = ('blog.add_post')
    success_url = reverse_lazy('blog:list')

    def form_valid(self, form):
        if form.is_valid():
            new_post = form.save()
            new_post.slug = slugify(new_post.title)
            new_post.save()
        return super().form_valid(form)


class PostUpdateView(LoginRequiredMixin, PermissionRequiredMixin, UpdateView):
    model = Post
    fields = ('title', 'content', 'author', 'preview_img')
    permission_required = ('blog.change_post')

    def form_valid(self, form):
        if form.is_valid():
            new_post = form.save()
            new_post.slug = slugify(new_post.title)
            new_post.save()
        return super().form_valid(form)

    def get_success_url(self):
        return reverse('blog:view', args=[self.kwargs.get('pk')])


class PostListView(LoginRequiredMixin, ListView):
    model = Post

    def get_queryset(self, *args, **kwargs):
        queryset = super().get_queryset(*args, **kwargs)
        queryset = queryset.filter(is_published=True)
        return queryset


class PostArchiveListView(LoginRequiredMixin, PermissionRequiredMixin, ListView):
    model = Post
    template_name = 'blog/post_archive_list.html'
    permission_required = ('blog.view_post')

    def get_queryset(self, *args, **kwargs):
        queryset = super().get_queryset(*args, **kwargs)
        queryset = queryset.filter(is_published=False)
        return queryset

    def get_success_url(self):
        return reverse_lazy('blog:archive')

class PostDetailView(LoginRequiredMixin, DetailView):
    model = Post

    def get_object(self, queryset=None):
        self.object = super().get_object(queryset)
        if self.object.is_published:
            self.object.views_count += 1
        self.object.save()
        return self.object

class PostDeleteView(LoginRequiredMixin, PermissionRequiredMixin, DeleteView):
    model = Post
    permission_required = ('blog.delete_post')
    if model.is_published:
        success_url = reverse_lazy('blog:list')
    else:
        success_url = reverse_lazy('blog:archive')


def toggle_is_published(request, pk):
    post_item = get_object_or_404(Post, pk=pk)
    if post_item.is_published:
        post_item.is_published = False
        post_item.save()

        return redirect(reverse_lazy('blog:list'))
    else:
        post_item.is_published = True
        post_item.save()

        return redirect(reverse_lazy('blog:archive'))

blog/templates/blog/post_archive_list.html
{% extends 'main/base.html' %}
{% block content %}
    <div class="col-12 mb-5">
        <a class="btn btn-outline-primary" href="{% url 'blog:create' %}">Добавить пост</a>
        <a class="btn btn-outline-primary" href="{% url 'blog:list' %}">Вернуться на главную страницу</a>
    </div>
            {% for object in object_list %}
            {% load imgs %}
            <div class="col-md-12">
              <div class="card mb-4 box-shadow">
                {% if object.preview_img %}
                    <img class="card-img-top" src="{{ object.preview_img | media }}" alt="фывфыв">
                {% endif %}
                <div class="card-body">
                  <p class="card-title">{{object.title | title}}</p>
                  <div class="d-flex justify-content-between align-items-center">
                      <p class="card-text ">{{object.content | slice:'101'}}</p>
                      </div>
                      <div class="btn-group">
                        <a class="btn btn-primary" href="{% url 'blog:view' object.pk %}" role="button">Читать</a>
                        <a class="btn btn-secondary" href="{% url 'blog:edit' object.pk %}" role="button">Редактировать</a>
                        <a class="btn btn-danger" href="{% url 'blog:delete' object.pk %}" role="button">Удалить</a>
                        <a class="btn btn-outline-success" href="{% url 'blog:is_published' object.pk %}" role="button">Опубликовать</a>


                    </div>

                </div>
              </div>
            </div>
            {% endfor %}
{% endblock %}

blog/templates/blog/post_confirm_delete.html
{% extends 'main/base.html' %}

{% block content %}
    <div class="col-12" xmlns="http://www.w3.org/1999/html">
    <div class="row">
        <div class="col-6">
            <div class="card">
                <div class="card-body">
                    <form method="post">
                        {% csrf_token %}
                        <p>Хотите удалить публикацию '{{ object.title }}'?</p>
                        <button type="submit" class="btn btn-danger">Удалить</button>
                        {% if object.is_published %}
                            <a href="{% url 'blog:list' %}" class="btn btn-secondary">Назад</a>
                        {% else %}
                            <a href="{% url 'blog:archive' %}" class="btn btn-secondary">Назад</a>
                        {% endif %}
                    </form>
                </div>
            </div>
        </div>
    </div>
    </div>


{% endblock %}

blog/templates/blog/post_detail.html
{% extends 'main/base.html' %}
{% block content %}
            {% load imgs %}
            <div class="col-md-12">
              <div class="card mb-12 box-shadow">
                {% if object.preview_img %}
                    <img class="card-img-top" src="{{ object.preview_img | media }}" alt="фывфыв">
                {% endif %}
                <div class="card-header">
                    <a class="card-title">Публикация: {{ object.title }} ({{ object.slug }})</a>
                    <p class="card-title"> Автор: {{ object.author }}</p>

                </div>
                <div class="card-body">
                    <p>
                        {{ object.content }}
                    </p>
                    </div>
                  <div class="card-footer">
                      <p class="card-text">Просмотры: {{ object.views_count }}</p>
                      <p class="card-text">Дата публикации: {{ object.date_posted }}</p>
                      {% if object.is_published %}
                          <a href="{% url 'blog:list' %}" class="btn btn-secondary">Назад</a>
                          <a class="btn btn-outline-secondary" href="{% url 'blog:is_published' object.pk %}" role="button">Убрать в архив</a>
                      {% else %}
                          <a href="{% url 'blog:archive' %}" class="btn btn-secondary">Назад</a>
                          <a class="btn btn-outline-success" href="{% url 'blog:is_published' object.pk %}" role="button">Опубликовать</a>
                      {% endif %}
                  </div>
                </div>
              </div>


{% endblock %}

blog/templates/blog/post_form.html
{% extends 'main/base.html' %}

{% block content %}
    <div class="col-12">
    <div class="row">
        <div class="col-6">
            <div class="card">
                <div class="card-body">
                    <form method="post">
                        {% csrf_token %}
                        {{ form.as_p }}
                        <button type="submit" class="btn btn-success">
                            {% if object %}
                                Сохранить
                            {% else %}
                                Создать
                            {% endif %}
                        </button>
                    <a href="{% url 'blog:list' %}" class="btn btn-secondary">Назад</a>
                    </form>
                </div>
            </div>
        </div>
    </div>
    </div>


{% endblock %}

blog/templates/blog/post_list.html
{% extends 'main/base.html' %}
{% block content %}
    <div class="col-12 mb-5">
        <a class="btn btn-outline-primary" href="{% url 'blog:create' %}">Добавить пост</a>
        <a class="btn btn-outline-secondary" href="{% url 'blog:archive' %}">Архив постов</a>
    </div>
            {% for object in object_list %}
            {% load imgs %}
            <div class="col-md-12">
              <div class="card mb-4 box-shadow">
                {% if object.preview_img %}
                    <img class="card-img-top" src="{{ object.preview_img | media }}" alt="фывфыв">
                {% endif %}
                <div class="card-body">
                  <p class="card-title">{{object.title | title}}</p>
                  <div class="d-flex justify-content-between align-items-center">
                      <p class="card-text ">{{object.content | slice:'101'}}</p>
                      </div>
                      <div class="btn-group">
                        <a class="btn btn-primary" href="{% url 'blog:view' object.pk %}" role="button">Читать</a>
                        <a class="btn btn-secondary" href="{% url 'blog:edit' object.pk %}" role="button">Редактировать</a>
                        <a class="btn btn-danger" href="{% url 'blog:delete' object.pk %}" role="button">Удалить</a>
                        <a class="btn btn-outline-secondary" href="{% url 'blog:is_published' object.pk %}" role="button">Убрать в архив</a>


                    </div>

                </div>
              </div>
            </div>
            {% endfor %}
{% endblock %}