blog/urls.py
from django.urls import path

from blog.views import PostCreateView, PostListView, PostDetailView, PostUpdateView, PostDeleteView, \
    toggle_is_published, PostArchiveListView
from blog.apps import BlogConfig

app_name = BlogConfig.name

urlpatterns = [
    path('create/', PostCreateView.as_view(), name='create'),
    path('', PostListView.as_view(), name='list'),
    path('edit/<int:pk>/', PostUpdateView.as_view(), name='edit'),
    path('view/<int:pk>/', PostDetailView.as_view(), name='view'),
    path('delete/<int:pk>/', PostDeleteView.as_view(), name='delete'),
    path('is_published/<int:pk>/', toggle_is_published, name='is_published'),
    path('archive/', PostArchiveListView.as_view(), name='archive'),

]

config/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls', namespace='main')),
    path('blog/', include('blog.urls', namespace='blog')),
    path('users/', include('users.urls', namespace='users')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

main/urls.py
from django.urls import path
from django.views.decorators.cache import cache_page

from main.views import ProductDetailView, ProductsListView, ContactView, ProductCreateView, ProductUpdateView, ProductDeleteView
from main.apps import MainConfig

app_name = MainConfig.name

urlpatterns = [
    path('', cache_page(60)(ProductsListView.as_view()), name='index'),
    path('contact/', ContactView.as_view(), name='contact',),
    path('product/<int:pk>/', cache_page(60)(ProductDetailView.as_view()), name='product'),
    path('create/', ProductCreateView.as_view(), name='create'),
    path('update/<int:pk>/', ProductUpdateView.as_view(), name='update'),
    path('delete/<int:pk>/', ProductDeleteView.as_view(), name='delete'),
]

users/urls.py
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path

from users.apps import UsersConfig
from users.views import RegisterView, ProfileView, user_verification, reset_password

app_name = UsersConfig.name





urlpatterns = [
    path('', LoginView.as_view(template_name='users/login.html'), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('register/', RegisterView.as_view(), name='register'),
    path('profile/', ProfileView.as_view(), name='profile'),
    path('email-confirm/<str:token>/', user_verification, name='email-confirm'),
    path('password-reset/', reset_password, name='password-reset'),

]

users/models.py
from django.contrib.auth.models import AbstractUser
from django.core.validators import RegexValidator
from django.db import models

# Create your models here.

class User(AbstractUser):
    phone = models.CharField(max_length=35, verbose_name='Телефон')
    avatar = models.ImageField(upload_to='users/', null=True, blank=True, verbose_name='Аватар')
    username = None
    email = models.EmailField(unique=True, verbose_name='E-mail')
    country = models.CharField(max_length=100, verbose_name='Страна', blank=True, null=True)

    token = models.CharField(max_length=100, verbose_name="Токен", blank=True, null=True)

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = []

users/forms.py
from django.contrib.auth.forms import UserCreationForm, UserChangeForm
from django import forms

from users.models import User


class UserRegistrationForm(UserCreationForm):

    class Meta:
        model = User
        fields = ('email', 'password1', 'password2')

class UserProfileForm(UserChangeForm):

    class Meta:
        model = User
        fields = ('first_name', 'last_name', 'email', 'phone', 'avatar', 'country')

        def __init__(self, *args, **kwargs):

            super().__init__(*args, **kwargs)

            self.fields['password'].widget = forms.HiddenInput()

users/views.py
import secrets
import string
import random

from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.mixins import LoginRequiredMixin
from django.core.mail import send_mail
from django.shortcuts import render, get_object_or_404, redirect
from django.urls import reverse_lazy, reverse
from django.views import generic

from config import settings
from config.settings import EMAIL_HOST_USER
from users.forms import UserRegistrationForm, UserProfileForm
from users.models import User


# Create your views here.


class RegisterView(generic.CreateView):
    model = User
    form_class = UserRegistrationForm
    template_name = "users/register.html"
    success_url = reverse_lazy("users:login")

    def form_valid(self, form):
        user = form.save()
        user.is_active = False
        token = secrets.token_hex(16)
        user.token = token
        user.save()
        host = self.request.get_host()
        url = f"http://{host}/users/email-confirm/{token}"
        send_mail(
            subject="Подтверждение почты",
            message=f"Перейдите по ссылке для подтверждения завершения регистрации: {url}",
            from_email=settings.EMAIL_HOST_USER,
            recipient_list=[user.email],
        )

        return super().form_valid(form)


def user_verification(request, token):
    user = get_object_or_404(User, token=token)
    user.is_active = True
    user.save()
    return redirect(reverse("users:login"))

class ProfileView(LoginRequiredMixin, generic.UpdateView):
    model = User
    form_class = UserProfileForm
    success_url = reverse_lazy("users:profile")

    def get_object(self, queryset=None):
        return self.request.user


def reset_password(request):

    if request.method == 'POST':
        email = request.POST.get('email')

        if not User.objects.filter(email=email).exists():
            return render(request, template_name='users/reset_password.html')
        else:
            user = get_object_or_404(User, email=email)
            new_password = ''.join(random.choices(string.ascii_letters + string.digits, k=8))
            user.set_password(new_password)
            user.save()
            send_mail(
                subject=f'Сброс пароля',
                message=f'Ваш новый пароль: {new_password}',
                from_email=EMAIL_HOST_USER,
                recipient_list=[email],
            )
        return redirect(reverse('users:login'))

    return render(request, template_name='users/reset_password.html')

users/templates/users/login.html
{% extends 'main/base.html' %}

{% block content %}
    <div class="container">
    <form class="row" method="post" enctype="multipart/form-data">
    <div class="col-3">

    </div>
        <div class="col-6">
            <div class="card">
                <div class="card-header">
                    <p class="card-text">Вход</p>
                </div>

                <div class="card-body">
                        {% csrf_token %}
                        {{ form.as_p }}
                </div>
                <div class="card-footer">
                        <button type="submit" class="btn btn-success">
                            Войти
                        </button>
                    <a href="{% url 'main:index' %}" class="btn btn-secondary">Назад</a>
                    <a href="{% url 'users:password-reset' %}" class="btn btn-outline-primary">Сброс пароля</a>
                </div>
            </div>
        </div>

    </form>
    </div>


{% endblock %}

users/templates/users/register.html
{% extends 'main/base.html' %}

{% block content %}
    <div class="container">
    <form class="row" method="post" enctype="multipart/form-data">
    <div class="col-3">

    </div>
        <div class="col-6">
            <div class="card">
                <div class="card-header">
                    <p class="card-text">Регистрация</p>
                </div>

                <div class="card-body">
                        {% csrf_token %}
                        {{ form.as_p }}
                </div>
                <div class="card-footer">
                        <button type="submit" class="btn btn-success">
                            Зарегистрироваться
                        </button>
                    <a href="{% url 'main:index' %}" class="btn btn-secondary">Назад</a>
                </div>
            </div>
        </div>

    </form>
    </div>


{% endblock %}

users/templates/users/reset_password.html
{% extends 'main/base.html' %}

{% block content %}
    <div class="container">
    <form class="row" method="post" enctype="multipart/form-data">
    <div class="col-3">

    </div>
        <div class="col-6">
            <div class="card">
                {% csrf_token %}
                <div class="card-header">
                    <p class="card-text">Сброс пароля</p>
                </div>

                <div class="card-body">
                        <label for="email" class="form-label">Почта:</label>
                <input type="email" class="form-control" id="email"
                       name="email" required autocomplete="email"
                >
                <h6 class="mt-2">На указанную почту будет отправлено письмо с новым паролем </h6>
                </div>
                <div class="card-footer">
                        <button type="submit" class="p-2 btn btn-outline-primary">Сбросить</button>
                    <a href="{% url 'main:index' %}" class="btn btn-secondary">Назад</a>
                </div>
            </div>
        </div>

    </form>
    </div>


{% endblock %}

users/templates/users/user_form.html
{% extends 'main/base.html' %}

{% block content %}
    <div class="container">
    <form class="row" method="post" enctype="multipart/form-data">
    <div class="col-3">

    </div>
        <div class="col-6">
            <div class="card">
                <div class="card-header">
                    <p class="card-text">Редактирование профиля</p>
                </div>

                <div class="card-body">
                        {% csrf_token %}
                        {{ form.as_p }}
                </div>
                <div class="card-footer">
                        <button type="submit" class="btn btn-success">
                            Подтвердить
                        </button>
                    <a href="{% url 'main:index' %}" class="btn btn-secondary">Назад</a>
                </div>
            </div>
        </div>

    </form>
    </div>


{% endblock %}