blog/urls.py
from django.urls import path

from blog.views import PostCreateView, PostListView, PostDetailView, PostUpdateView, PostDeleteView, \
    toggle_is_published, PostArchiveListView
from blog.apps import BlogConfig

app_name = BlogConfig.name

urlpatterns = [
    path('create/', PostCreateView.as_view(), name='create'),
    path('', PostListView.as_view(), name='list'),
    path('edit/<int:pk>/', PostUpdateView.as_view(), name='edit'),
    path('view/<int:pk>/', PostDetailView.as_view(), name='view'),
    path('delete/<int:pk>/', PostDeleteView.as_view(), name='delete'),
    path('is_published/<int:pk>/', toggle_is_published, name='is_published'),
    path('archive/', PostArchiveListView.as_view(), name='archive'),

]

config/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls', namespace='main')),
    path('blog/', include('blog.urls', namespace='blog')),
    path('users/', include('users.urls', namespace='users')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

main/urls.py
from django.urls import path
from django.views.decorators.cache import cache_page

from main.views import ProductDetailView, ProductsListView, ContactView, ProductCreateView, ProductUpdateView, ProductDeleteView
from main.apps import MainConfig

app_name = MainConfig.name

urlpatterns = [
    path('', cache_page(60)(ProductsListView.as_view()), name='index'),
    path('contact/', ContactView.as_view(), name='contact',),
    path('product/<int:pk>/', cache_page(60)(ProductDetailView.as_view()), name='product'),
    path('create/', ProductCreateView.as_view(), name='create'),
    path('update/<int:pk>/', ProductUpdateView.as_view(), name='update'),
    path('delete/<int:pk>/', ProductDeleteView.as_view(), name='delete'),
]

main/models.py
from django.db import models

from users.models import User

# Create your models here.

NULLABLE = {"blank": True, "null": True}


class Category(models.Model):
    name = models.CharField(max_length=50, verbose_name="Категория")
    description = models.CharField(max_length=150, verbose_name="Описание")

    def __str__(self):
        return f"{self.name}"

    class Meta:
        verbose_name = "Категория"
        verbose_name_plural = "Категории"


class Product(models.Model):
    name = models.CharField(max_length=50, verbose_name="Название")
    description = models.TextField(max_length=150, verbose_name="Описание")
    img = models.ImageField(upload_to="products_img/", verbose_name="Фото", **NULLABLE)
    category = models.ForeignKey(
        Category, on_delete=models.CASCADE, related_name="Категория"
    )
    price = models.PositiveIntegerField(verbose_name="Цена")
    created_at = models.DateTimeField(verbose_name="Дата создания", auto_now_add=True)
    updated_at = models.DateTimeField(
        verbose_name="Дата последнего изменения", auto_now=True
    )
    seller = models.ForeignKey(User, verbose_name="Продавец", help_text="", blank=True, null=True, on_delete=models.CASCADE)
    is_published = models.BooleanField(default=True, verbose_name="Опубликовано")

    def __str__(self):
        return f"{self.name} ({self.category}) - {self.price}"

    class Meta:
        verbose_name = "Продукт"
        verbose_name_plural = "Продукты"
        permissions = [
            ("can_publicate_product", "Can publicate product"),
        ]


class Version(models.Model):
    product = models.ForeignKey(
        Product,
        on_delete=models.SET_NULL,
        related_name="version",
        null=True,
        blank=True,
        verbose_name="Продукт",
    )
    version_index = models.CharField(max_length=20, verbose_name="Номер версии")
    version_name = models.CharField(max_length=150, verbose_name="Название")
    is_actual = models.BooleanField(default=False, verbose_name="Актуальная версия")

    def __str__(self):
        return f"{self.version_name} ({self.version_index})"

    class Meta:
        verbose_name = "Версия"
        verbose_name_plural = "Версии"

main/forms.py
from django import forms
from django.forms import BooleanField

from main.models import Product, Version


blocked_words = ['казино', 'криптовалюта', 'крипта', 'биржа', 'дешево', 'бесплатно', 'обман', 'полиция', 'радар']


class StyleMixin:
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            if isinstance(field, BooleanField):
                field.widget.attrs['class'] = 'form-check'
            else:
                field.widget.attrs['class'] = 'form-control'


class ProductForm(StyleMixin, forms.ModelForm):
    class Meta:
        model = Product
        exclude = ('seller',)

    def clean_name(self):
        cleaned_data = self.cleaned_data['name']

        for word in blocked_words:
            if word.lower() in cleaned_data.lower():
                raise forms.ValidationError("В названии содержатся запрещенные слова")

        return cleaned_data

    def clean_description(self):
        cleaned_data = self.cleaned_data['description']

        for word in blocked_words:
            if word.lower() in cleaned_data.lower():
                raise forms.ValidationError("В описании содержатся запрещенные слова")

        return cleaned_data


class ProductModeratorForm(StyleMixin, forms.ModelForm):
    class Meta:

        model = Product
        fields = ('is_published','description','category')


class VersionForm(StyleMixin, forms.ModelForm):

    class Meta:
        model = Version
        fields = '__all__'

    def clean_version_index(self):
        cleaned_data = self.cleaned_data['version_index']

        for word in blocked_words:
            if word.lower() in cleaned_data.lower():
                raise forms.ValidationError("В названии содержатся запрещенные слова")

        return cleaned_data

    def clean_version_name(self):
        cleaned_data = self.cleaned_data['version_name']

        for word in blocked_words:
            if word.lower() in cleaned_data.lower():
                raise forms.ValidationError("В названии содержатся запрещенные слова")

        return cleaned_data

main/views.py
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin
from django.core.exceptions import PermissionDenied
from django.forms import inlineformset_factory
from django.urls import reverse_lazy, reverse

from main.forms import ProductForm, VersionForm, ProductModeratorForm
from main.models import Product, Version
from django.views.generic import ListView, DetailView, TemplateView, CreateView, UpdateView, DeleteView

from main.services import get_caches_versions_for_products


class ProductsListView(LoginRequiredMixin, ListView):
    model = Product


class ProductCreateView(LoginRequiredMixin, PermissionRequiredMixin, CreateView):
    model = Product
    form_class = ProductForm
    permission_required = 'main.add_product'
    success_url = reverse_lazy('main:index')

    def get_context_data(self, **kwargs):
        context_data = super().get_context_data(**kwargs)
        VersionFormset = inlineformset_factory(Product, Version, form=VersionForm, extra=1)

        if self.request.method == 'POST':
            context_data['formset'] = VersionFormset(self.request.POST, instance=self.object)
        else:
            context_data['formset'] = VersionFormset(instance=self.object)

        return context_data

    def form_valid(self, form):
        product = form.save()
        user = self.request.user
        product.seller = user
        product.save()

        context = self.get_context_data()
        formset = context['formset']
        if form.is_valid() and formset.is_valid():
            self.object = form.save()
            formset.instance = self.object
            formset.save()
            return super().form_valid(form)

        else:
            return self.render_to_response(self.get_context_data(form=form, formset=formset))


class ProductUpdateView(LoginRequiredMixin, PermissionRequiredMixin, UpdateView):
    model = Product
    form_class = ProductForm
    permission_required = 'main.change_product'
    success_url = reverse_lazy('main:product')

    def get_success_url(self):
        return reverse('main:product', args=[self.kwargs.get('pk')])

    def get_context_data(self, **kwargs):
        context_data = super().get_context_data(**kwargs)
        VersionFormset = inlineformset_factory(Product, Version, form=VersionForm, extra=1)

        if self.request.method == 'POST':
            context_data['formset'] = VersionFormset(self.request.POST, instance=self.object)
        else:
            context_data['formset'] = VersionFormset(instance=self.object)

        return context_data

    def get_form_class(self):
        user = self.request.user

        if user == self.object.seller:
            return ProductForm
        if user.has_perm('main.can_publicate_product'):
            return ProductModeratorForm
        raise PermissionDenied

    def form_valid(self, form):
        context = self.get_context_data()
        formset = context['formset']
        if form.is_valid() and formset.is_valid():
            self.object = form.save()
            formset.instance = self.object
            formset.save()
            return super().form_valid(form)

        else:
            return self.render_to_response(self.get_context_data(form=form, formset=formset))


class ProductDetailView(LoginRequiredMixin, DetailView):
    model = Product

    def get_context_data(self, **kwargs):
        context_data = super().get_context_data(**kwargs)
        context_data['versions'] = get_caches_versions_for_products(self.object.pk)

        return context_data


class ContactView(LoginRequiredMixin, TemplateView):
    template_name = 'main/contact.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'Свяжитесь с нами'


class ProductDeleteView(LoginRequiredMixin, PermissionRequiredMixin, DeleteView):
    model = Product
    success_url = reverse_lazy('main:index')
    permission_required = 'main.delete_product'

main/templates/main/base.html
{% load static %}
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="/docs/4.0/assets/img/favicons/favicon.ico">

    <title>{{ title }}</title>

    <link rel="canonical" href="https://getbootstrap.com/docs/4.0/examples/album/">

    <!-- Bootstrap core CSS -->
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">

    <!-- Custom styles for this template -->
    <link href="{% static 'css/album.css' %}" rel="stylesheet">
  </head>

  <body>

    <header>
      <div class="collapse bg-dark" id="navbarHeader">
        <div class="container">
          <div class="row">
            <div class="col-sm-8 col-md-7 py-4">
            </div>
            {% include 'main/includes/inc_main_menu.html' %}
          </div>
        </div>
      </div>
      <div class="navbar navbar-dark bg-dark box-shadow">
        <div class="container d-flex justify-content-between">
          <a href="#" class="navbar-brand d-flex align-items-center">
            <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="mr-2"><path d="M23 19a2 2 0 0 1-2 2H3a2 2 0 0 1-2-2V8a2 2 0 0 1 2-2h4l2-3h6l2 3h4a2 2 0 0 1 2 2z"></path><circle cx="12" cy="13" r="4"></circle></svg>
            <strong>Album</strong>
          </a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarHeader" aria-controls="navbarHeader" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
        </div>
      </div>
    </header>

    <main role="main">

      <section class="jumbotron text-center">
        <div class="container">
          <h1 class="jumbotron-heading">{{ title }}</h1>

          </p>
        </div>
      </section>

      <div class="album py-5 bg-light">
        <div class="container">

          <div class="row">
              {% block content %}
              {% endblock %}
          </div>
        </div>
      </div>

    </main>

    <footer class="text-muted">
      <div class="container">
        <p class="float-right">
          <a href="#">Back to top</a>
        </p>
        <p>&copy; {% now 'Y' %}</p>
        <p>New to Bootstrap? <a href="../../">Visit the homepage</a> or read our <a href="../../getting-started/">getting started guide</a>.</p>
      </div>
    </footer>

    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script>window.jQuery || document.write('<script src="../../assets/js/vendor/jquery-slim.min.js"><\/script>')</script>
    <script src="{% static 'js/vendor/popper.min.js' %}"></script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
    <script src="{% static 'js/vendor/holder.min.js' %}"></script>
  </body>
</html>

main/templates/main/contact.html
{% extends 'main/base.html' %}

{% block content %}
            <div class="col-md-4">
              <div class="card mb-4 box-shadow">
                <div class="card-body">
                  <p class="card-text">
                      Офис МСК<br>
                      Офис СПб
                  </p>

                </div>
              </div>
            </div>
            <div class="col-md-4">
              <div class="card mb-4 box-shadow">
                <div class="card-body">
                    <h2>
                        Свяжитесь с нами!
                    </h2>
                 <form method="post">
                     {% csrf_token %}

                     <div class="mb-3">
                          <label for="exampleFormControlInput1" class="form-label">Введите E-mail</label>
                          <input type="email" class="form-control" id="exampleFormControlInput1" placeholder="name@example.com">
                     </div>
                     <div class="mb-3">
                          <label for="exampleFormControlTextarea1" class="form-label">Ваше сообщение</label>
                          <textarea class="form-control" id="exampleFormControlTextarea1" rows="3"></textarea>
                     </div>
                     <button type="submit" class="mb-2 btn btn-primary form_control">
                         Отправить
                     </button>

                 </form>
{% endblock %}

main/templates/main/index.html
{% extends 'main/base.html' %}
{% block content %}
            {% for object in object_list %}
            {% load imgs %}
            <div class="col-md-4">
              <div class="card mb-4 box-shadow">
                <img class="card-img-top" src="{{ object.img| media }}" >
                <div class="card-body">
                  <p class="card-title">{{object.name | title}}</p>
                    <p class="card-subtitle text-muted">Цена: {{object.price}} р.</p>
                  <div class="d-flex justify-content-between align-items-center">
                      <p class="card-text ">{{object.description | slice:'101'}}</p>
                      </div>
                      <div class="btn">
                        <a class="btn btn-primary" href="product/{{object.pk}}" role="button">Подробнее</a>
                    </div>

                </div>
              </div>
            </div>
            {% endfor %}
{% endblock %}

main/templates/main/product.html
{% extends 'main/base.html' %}
{% block content %}
            {% load imgs %}
            <div class="col-md-12">
              <div class="card mb-12 box-shadow">
                <img class="card-img-top" src="{{ img | media }}" >
                <div class="card-body">
                  <h4 class="card-text">{{name}}</h4>
                  <h5 class="card-text">Цена: {{price}} р.</h5>
                    <p class="card-text ">Категория: {{category | slice:'101'}}</p>
                  <div class="d-flex justify-content-between align-items-center">
                    <p class="card-text">{{description}}</p>
                    <div class="btn">
                      <button type="button" class="w-100 btn btn-lg btn-outline-success btn-success text-black ">Купить</button>
                    </div>
                  </div>
                </div>
              </div>
            </div>

{% endblock %}

main/templates/main/product_confirm_delete.html
{% extends 'main/base.html' %}

{% block content %}
    <div class="col-12" xmlns="http://www.w3.org/1999/html">
    <div class="row">
        <div class="col-6">
            <div class="card">
                <div class="card-body">
                    <form method="post">
                        {% csrf_token %}
                        <p>Хотите удалить продукт '{{ object.title }}'?</p>
                        <button type="submit" class="btn btn-danger">Удалить</button>
                            <a href="{% url 'main:index' %}" class="btn btn-secondary">Назад</a>
                    </form>
                </div>
            </div>
        </div>
    </div>
    </div>


{% endblock %}

main/templates/main/product_detail.html
{% extends 'main/base.html' %}
{% block content %}
            {% load imgs %}
            <div class="col-md-6">
              <div class="card mb-12 box-shadow">
                  {% if object.img %}
                    <img class="card-img-top" src="{{ object.img | media }}" alt="фывфыв">
                {% endif %}
                <div class="card-header">
                  <h4 class="card-text">{{object.name}}</h4>
                </div>
                <div class="card-body">
                  <h5 class="card-text">Цена: {{object.price}} р.</h5>
                    <p class="card-text ">Категория: {{object.category | slice:'101'}}</p>
                  <div class="d-flex justify-content-between align-items-center">
                    <p class="card-text">{{object.description}}</p>
                  </div>
                <div class="card-footer">
                    <div class="btn">
                      <button type="button" class="w-100 btn btn-lg btn-outline-success btn-success text-black ">Купить</button>
                    </div>
              </div>
                  </div>
                </div>
              </div>
            <div class="col-md-6">
                <div class="card mb-12 box-shadow">

                <div class="card-header">
                  <h4 class="card-text">Версии продукта</h4>
                </div>
                <div class="card-body">
                <ul>
                    {% for version in versions %}
                        <li>
                        {{ version }}
                        </li>
                    {% endfor %}
                </ul>

                  </div>
                <div class="card-footer">

              </div>
                  </div>
                </div>
            </div>


{% endblock %}

main/templates/main/product_form.html
{% extends 'main/base.html' %}

{% block content %}
    <div class="container">
    <form class="row" method="post" enctype="multipart/form-data">
        <div class="col-6">
            <div class="card">
                <div class="card-header">
                    <p class="card-text">Продукт</p>
                </div>

                <div class="card-body">
                        {% csrf_token %}
                        {{ form.as_p }}
                </div>
                <div class="card-footer">
                        <button type="submit" class="btn btn-success">
                            {% if object %}
                                Сохранить
                            {% else %}
                                Создать
                            {% endif %}
                        </button>
                    <a href="{% url 'main:index' %}" class="btn btn-secondary">Назад</a>
                </div>
            </div>
        </div>
    <div class="col-6">
            <div class="card">
            <div class="card-header">
                <p class="card-text">Версия</p>
            </div>
                <div class="card-body">
                        {{ formset.management_form }}
                        {% for form in formset.forms %}

                        {{ form.as_p }}
                        {% endfor %}
                </div>
            </div>
        </div>
    </form>
    </div>


{% endblock %}

main/templates/main/product_list.html
{% extends 'main/base.html' %}
{% block content %}
    <div class="col-12 mb-4">
    {% if perms.main.add_product %}
        <a class="btn btn-outline-primary" href="{% url 'main:create' %}">Добавить продукт</a>
    {% endif %}
    </div>
            {% for object in object_list %}
            {% load imgs %}
                {% if object.is_published or perms.main.can_publicate_product%}
            <div class="col-4">
              <div class="card  box-shadow">
                  {% if object.img %}
                    <img class="card-img-top" src="{{ object.img | media }}" alt="фывфыв">
                {% endif %}
                <div class="card-header">
                    <p class="card-title">
                        {{object.name | title}}
                    </p>
                    {% if object.is_published == False %}
                        <p class="text-danger  ">(Не опуликовано)</p>
                      {% endif %}
                </div>
                <div class="card-body">
                    <p class="card-subtitle text-muted">Цена: {{object.price}} р.</p>
                    <div class="d-flex justify-content-between align-items-center">
                        <p class="card-text ">{{object.description | slice:'101'}}</p>
                      {% for version in object.version.all %}
                                   {% if version.is_actual %}
                                 <p>Версия: {{ version.version_index }} ({{ version.version_name }})</p>
                                    {% endif %}
                                     {% endfor %}
                      </div>
                </div>

                <div class="card-footer">

                      <div class="btn-group btn-group-sm">
                        <a class="btn btn-primary" href="{% url 'main:product' object.pk %}" role="button">Подробнее</a>
                          {% if user == object.seller or perms.main.can_change %}

                        <a class="btn btn-secondary" href="{% url 'main:update' object.pk %}" role="button">Редактировать</a>
                              {% endif %}
                      {% if user == object.seller %}
                        <a class="btn btn-danger" href="{% url 'main:delete' object.pk %}" role="button">Удалить</a>
                          {% endif %}

                    </div>
                </div>

                </div>
              </div>

            {% endif %}
            {% endfor %}
{% endblock %}